name: LevelUp Bot (Tech Coder Sim)

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  workflow_dispatch:

jobs:
  levelup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y
          npm install @octokit/rest dayjs

      - name: Run updater
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node update_xp.js

      - name: Commit README changes
        run: |
          git config user.name "LevelUp Bot"
          git config user.email "levelup-bot@example.com"
          git add README.md
          git commit -m "🔼 Auto-update Dev XP (LevelUp Bot)" || echo "No changes to commit"
          git push
